// Code generated by https://be; DO NOT EDIT.

package config

import (
	"github.com/go-dev-frame/sponge/pkg/conf"
)

var config *Config

func Init(configFile string, fs ...func()) error {
	config = &Config{}
	return conf.Parse(configFile, config, fs...)
}

func Show(hiddenFields ...string) string {
	return conf.Show(config, hiddenFields...)
}

func Get() *Config {
	if config == nil {
		panic("config is nil, please call config.Init() first")
	}
	return config
}

func Set(conf *Config) {
	config = conf
}

type Config struct {
	App            App            `yaml:"app" json:"app"`
	Consul         Consul         `yaml:"consul" json:"consul"`
	Database       Database       `yaml:"database" json:"database"`
	Proxy          Proxy          `yaml:"proxy" json:"proxy"`
	FearGreedIndex FearGreedIndex `yaml:"fearGreedIndex" json:"fearGreedIndex"`
	DeepSeek       DeepSeek       `yaml:"deepseek" json:"deepseek"`
	Polymarket     Polymarket     `yaml:"polymarket" json:"polymarket"`
	Binance        Binance        `yaml:"binance" json:"binance"`
	GNews          GNews          `yaml:"gnews" json:"gnews"`
	CryptoQuant    CryptoQuant    `yaml:"cryptoquant" json:"cryptoquant"`
	Strategy       Strategy       `yaml:"strategy" json:"strategy"`
	Monitoring     Monitoring     `yaml:"monitoring" json:"monitoring"`
	Vault          Vault          `yaml:"vault" json:"vault"`
	Asynq          Asynq          `yaml:"asynq" json:"asynq"`
	Etcd           Etcd           `yaml:"etcd" json:"etcd"`
	Grpc           Grpc           `yaml:"grpc" json:"grpc"`
	GrpcClient     []GrpcClient   `yaml:"grpcClient" json:"grpcClient"`
	HTTP           HTTP           `yaml:"http" json:"http"`
	JWT            JWT            `yaml:"jwt" json:"jwt"`
	Jaeger         Jaeger         `yaml:"jaeger" json:"jaeger"`
	Logger         Logger         `yaml:"logger" json:"logger"`
	NacosRd        NacosRd        `yaml:"nacosRd" json:"nacosRd"`
	Redis          Redis          `yaml:"redis" json:"redis"`
}

type JWT struct {
	SignKey    string `yaml:"signKey" json:"signKey"`
	ExpireTime int    `yaml:"expireTime" json:"expireTime"`
	Issuer     string `yaml:"issuer" json:"issuer"`
}

type Consul struct {
	Addr string `yaml:"addr" json:"addr"`
}

type Etcd struct {
	Addrs []string `yaml:"addrs" json:"addrs"`
}

type Jaeger struct {
	AgentHost string `yaml:"agentHost" json:"agentHost"`
	AgentPort int    `yaml:"agentPort" json:"agentPort"`
}

type ClientToken struct {
	AppID  string `yaml:"appID" json:"appID"`
	AppKey string `yaml:"appKey" json:"appKey"`
	Enable bool   `yaml:"enable" json:"enable"`
}

type ClientSecure struct {
	CaFile     string `yaml:"caFile" json:"caFile"`
	CertFile   string `yaml:"certFile" json:"certFile"`
	KeyFile    string `yaml:"keyFile" json:"keyFile"`
	ServerName string `yaml:"serverName" json:"serverName"`
	Type       string `yaml:"type" json:"type"`
}

type ServerSecure struct {
	CaFile   string `yaml:"caFile" json:"caFile"`
	CertFile string `yaml:"certFile" json:"certFile"`
	KeyFile  string `yaml:"keyFile" json:"keyFile"`
	Type     string `yaml:"type" json:"type"`
}

type TLS struct {
	CertFile   string `yaml:"certFile" json:"certFile"`
	Domain     string `yaml:"domain" json:"domain"`
	Email      string `yaml:"email" json:"email"`
	EnableMode string `yaml:"enableMode" json:"enableMode"`
	KeyFile    string `yaml:"keyFile" json:"keyFile"`
}

type App struct {
	CacheType             string  `yaml:"cacheType" json:"cacheType"`
	EnableCircuitBreaker  bool    `yaml:"enableCircuitBreaker" json:"enableCircuitBreaker"`
	EnableHTTPProfile     bool    `yaml:"enableHTTPProfile" json:"enableHTTPProfile"`
	EnableLimit           bool    `yaml:"enableLimit" json:"enableLimit"`
	EnableMetrics         bool    `yaml:"enableMetrics" json:"enableMetrics"`
	EnableStat            bool    `yaml:"enableStat" json:"enableStat"`
	EnableTrace           bool    `yaml:"enableTrace" json:"enableTrace"`
	Env                   string  `yaml:"env" json:"env"`
	Host                  string  `yaml:"host" json:"host"`
	Name                  string  `yaml:"name" json:"name"`
	RegistryDiscoveryType string  `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	TracingSamplingRate   float64 `yaml:"tracingSamplingRate" json:"tracingSamplingRate"`
	Version               string  `yaml:"version" json:"version"`
}

type GrpcClient struct {
	ClientSecure          ClientSecure `yaml:"clientSecure" json:"clientSecure"`
	ClientToken           ClientToken  `yaml:"clientToken" json:"clientToken"`
	Host                  string       `yaml:"host" json:"host"`
	Name                  string       `yaml:"name" json:"name"`
	Port                  int          `yaml:"port" json:"port"`
	RegistryDiscoveryType string       `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	Timeout               int          `yaml:"timeout" json:"timeout"`
}

type Sqlite struct {
	ConnMaxLifetime int    `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	DBFile          string `yaml:"dbFile" json:"dbFile"`
	EnableLog       bool   `yaml:"enableLog" json:"enableLog"`
	MaxIdleConns    int    `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxOpenConns    int    `yaml:"maxOpenConns" json:"maxOpenConns"`
}

type Mysql struct {
	ConnMaxLifetime int      `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	Dsn             string   `yaml:"dsn" json:"dsn"`
	EnableLog       bool     `yaml:"enableLog" json:"enableLog"`
	MastersDsn      []string `yaml:"mastersDsn" json:"mastersDsn"`
	MaxIdleConns    int      `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxOpenConns    int      `yaml:"maxOpenConns" json:"maxOpenConns"`
	SlavesDsn       []string `yaml:"slavesDsn" json:"slavesDsn"`
}

type Postgresql struct {
	ConnMaxLifetime int    `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	Dsn             string `yaml:"dsn" json:"dsn"`
	EnableLog       bool   `yaml:"enableLog" json:"enableLog"`
	MaxIdleConns    int    `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxOpenConns    int    `yaml:"maxOpenConns" json:"maxOpenConns"`
}

type Redis struct {
	DialTimeout  int    `yaml:"dialTimeout" json:"dialTimeout"`
	Dsn          string `yaml:"dsn" json:"dsn"`
	KeyPrefix    string `yaml:"keyPrefix" json:"keyPrefix"`
	ReadTimeout  int    `yaml:"readTimeout" json:"readTimeout"`
	WriteTimeout int    `yaml:"writeTimeout" json:"writeTimeout"`
}

type Database struct {
	Driver     string     `yaml:"driver" json:"driver"`
	Mongodb    Mongodb    `yaml:"mongodb" json:"mongodb"`
	Mysql      Mysql      `yaml:"mysql" json:"mysql"`
	Postgresql Postgresql `yaml:"postgresql" json:"postgresql"`
	Sqlite     Sqlite     `yaml:"sqlite" json:"sqlite"`
}

type Mongodb struct {
	Dsn string `yaml:"dsn" json:"dsn"`
}

type Grpc struct {
	EnableToken  bool         `yaml:"enableToken" json:"enableToken"`
	HTTPPort     int          `yaml:"httpPort" json:"httpPort"`
	Port         int          `yaml:"port" json:"port"`
	ServerSecure ServerSecure `yaml:"serverSecure" json:"serverSecure"`
}

type Logger struct {
	Format string `yaml:"format" json:"format"`
	IsSave bool   `yaml:"isSave" json:"isSave"`
	Level  string `yaml:"level" json:"level"`
}

type NacosRd struct {
	IPAddr      string `yaml:"ipAddr" json:"ipAddr"`
	NamespaceID string `yaml:"namespaceID" json:"namespaceID"`
	Port        int    `yaml:"port" json:"port"`
}

type HTTP struct {
	Port    int `yaml:"port" json:"port"`
	Timeout int `yaml:"timeout" json:"timeout"`
	TLS     TLS `yaml:"tls" json:"tls"`
}

type DeepSeek struct {
	APIKey            string `yaml:"apiKey" json:"apiKey"`
	BaseURL           string `yaml:"baseURL" json:"baseURL"`
	Model             string `yaml:"model" json:"model"`
	UseAgentPredictor bool   `yaml:"useAgentPredictor" json:"useAgentPredictor"` // true=使用 DeepAgent 多智能体架构, false=使用传统单模型
}

type Polymarket struct {
	ClobAPIURL  string `yaml:"clobApiUrl" json:"clobApiUrl"`
	GammaAPIURL string `yaml:"gammaApiUrl" json:"gammaApiUrl"`
	ChainID     int    `yaml:"chainId" json:"chainId"`
	PrivateKey  string `yaml:"privateKey" json:"privateKey"`
	APIKey      string `yaml:"apiKey" json:"apiKey"`
	APISecret   string `yaml:"apiSecret" json:"apiSecret"`
	Passphrase  string `yaml:"passphrase" json:"passphrase"`
	WSMarketURL string `yaml:"wsMarketUrl" json:"wsMarketUrl"`
}

type Binance struct {
	APIURL string `yaml:"apiUrl" json:"apiUrl"`
}

type GNews struct {
	BaseURL string `yaml:"baseUrl" json:"baseUrl"`
	APIKey  string `yaml:"apiKey" json:"apiKey"`
}

type CryptoQuant struct {
	APIKey  string `yaml:"apiKey" json:"apiKey"`
	BaseURL string `yaml:"baseUrl" json:"baseUrl"`
}

// Proxy 代理配置（可选）
type Proxy struct {
	Addr string `yaml:"addr" json:"addr"` // 代理地址，如 "127.0.0.1:6450"，为空时不使用代理
}

// FearGreedIndex 恐慌贪婪指数配置
type FearGreedIndex struct {
	URL string `yaml:"url" json:"url"`
}

type Strategy struct {
	MinEdge              float64 `yaml:"minEdge" json:"minEdge"`
	MinConfidence        float64 `yaml:"minConfidence" json:"minConfidence"`
	MaxPositionPct       float64 `yaml:"maxPositionPct" json:"maxPositionPct"`
	KellyMultiplier      float64 `yaml:"kellyMultiplier" json:"kellyMultiplier"`
	TakeProfitFactor     float64 `yaml:"takeProfitFactor" json:"takeProfitFactor"`
	StopLossFactor       float64 `yaml:"stopLossFactor" json:"stopLossFactor"`
	PreResolutionMinutes int     `yaml:"preResolutionMinutes" json:"preResolutionMinutes"`
}

type Monitoring struct {
	PriceCheckInterval  int `yaml:"priceCheckInterval" json:"priceCheckInterval"`
	AlertPriceChangePct int `yaml:"alertPriceChangePct" json:"alertPriceChangePct"`
	MaxRetry            int `yaml:"maxRetry" json:"maxRetry"`
}

type Vault struct {
	RPCURL               string `yaml:"rpcUrl" json:"rpcUrl"`                             // 链上RPC节点地址
	ContractAddress      string `yaml:"contractAddress" json:"contractAddress"`           // PolyVault合约地址
	StrategistPrivateKey string `yaml:"strategistPrivateKey" json:"strategistPrivateKey"` // 策略角色私钥（用于withdrawToStrategy/depositFromStrategy签名）
}

type Asynq struct {
	Addr        string `yaml:"addr" json:"addr"`
	Password    string `yaml:"password" json:"password"`
	DB          int    `yaml:"db" json:"db"`
	Concurrency int    `yaml:"concurrency" json:"concurrency"`
}
